name: package build
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - '*'
jobs:
  build_rpms:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: build packages
      run: './build-all.sh'
    - name: upload rpms
      uses: actions/upload-artifact@v2
      with:
        name: RPMS
        path: RPMS/
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn` 

